// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTIataaMB3ci2_8sC8CuqTDFjbYJpkrOM',
    appId: '1:656609587905:web:33bf9b897f689903199a40',
    messagingSenderId: '656609587905',
    projectId: 'com-ex-safesync',
    authDomain: 'com-ex-safesync.firebaseapp.com',
    storageBucket: 'com-ex-safesync.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEQ3ezso22O3oNGL9SL86vOlt3Jhg3wHs',
    appId: '1:656609587905:android:d41f1815e907964f199a40',
    messagingSenderId: '656609587905',
    projectId: 'com-ex-safesync',
    storageBucket: 'com-ex-safesync.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb4ANO9CKcQ66oWmVA78cjXGlYr1i9hiE',
    appId: '1:656609587905:ios:d4b2702e45bffb8d199a40',
    messagingSenderId: '656609587905',
    projectId: 'com-ex-safesync',
    storageBucket: 'com-ex-safesync.appspot.com',
    iosBundleId: 'com.example.safesyncFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb4ANO9CKcQ66oWmVA78cjXGlYr1i9hiE',
    appId: '1:656609587905:ios:7565a82bdca53b1f199a40',
    messagingSenderId: '656609587905',
    projectId: 'com-ex-safesync',
    storageBucket: 'com-ex-safesync.appspot.com',
    iosBundleId: 'com.example.safesyncFrontend.RunnerTests',
  );
}
